//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOINTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPOINTMENT()
        {
            this.REFERRAL = new HashSet<REFERRAL>();
            this.PROCEDURE = new HashSet<PROCEDURE>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> REFERRAL_ID { get; set; }
        public System.Guid DOCTOR_SPECIALITY_ID { get; set; }
        public short PARAMETR_ID { get; set; }
        public System.DateTime DATETIME { get; set; }
        public string PATIENT_ID { get; set; }
    
        public virtual PATIENT PATIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REFERRAL> REFERRAL { get; set; }
        public virtual DOCTOR_SPECIALITY DOCTOR_SPECIALITY { get; set; }
        public virtual REPORT REPORT { get; set; }
        public virtual APPOINTMENT_PARAMETR APPOINTMENT_PARAMETR { get; set; }
        public virtual REFERRAL REFERRAL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCEDURE> PROCEDURE { get; set; }
    }
}
