//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR_RECEPTION_HOURS
    {
        public string Доктор { get; set; }
        public string Специальность { get; set; }
        public Nullable<System.TimeSpan> Час_начала_приема { get; set; }
        public Nullable<System.TimeSpan> Час_конца_приема { get; set; }
        public string День_недели_приема { get; set; }
        public long RowNum { get; set; }
    }
}
