//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR_SPECIALITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTOR_SPECIALITY()
        {
            this.APPOINTMENT = new HashSet<APPOINTMENT>();
            this.RECEPTION_HOURS = new HashSet<RECEPTION_HOURS>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid SPECIALITY_ID { get; set; }
        public System.Guid DOCTOR_ID { get; set; }
        public bool IS_VALID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPOINTMENT> APPOINTMENT { get; set; }
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual SPECIALITY SPECIALITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEPTION_HOURS> RECEPTION_HOURS { get; set; }
    }
}
