//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPTION_HOURS
    {
        public System.Guid DOCTOR_SPECIALITY_ID { get; set; }
        public int NUMBER_OF_DAY_WEEK { get; set; }
        public System.TimeSpan HOUR_START { get; set; }
        public System.TimeSpan HOUR_END { get; set; }
    
        public virtual DOCTOR_SPECIALITY DOCTOR_SPECIALITY { get; set; }
    }
}
