//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT
    {
        public System.Guid APPOINTMENT_ID { get; set; }
        public string DIAGNOSIS { get; set; }
        public string PRESCRIPTION { get; set; }
    
        public virtual APPOINTMENT APPOINTMENT { get; set; }
    }
}
